### ISSUE TITLE
[TS-654] Failed "shards install"

### ISSUE THREAD

**Issue by Eldomir** [codacy/codacy-ameba#31]
Tried to install ameba, got the following error:

Called macro defined in /home/linuxbrew/.linuxbrew/Cellar/crystal/1.10.1/share/crystal/src/yaml/serialization.cr:188:7

 188 | {% begin %}

Which expanded to:

 > 75 |                   
 > 76 | 
 > 77 |                   __temp_739 =
                          ^
Error: type must be Ameba::Severity, not (Ameba::Severity | Nil)

**Comment by veelenga** [comment]
Should be fixed by https://github.com/codacy/codacy-ameba/pull/29
Relates to https://github.com/crystal-ameba/ameba/issues/395
